CUDA_VISIBLE_DEVICES=0,1 accelerate launch --config_file /kaggle/working/test_code_gradient/src/config/config_fsdp_t5.yaml /kaggle/working/test_code_gradient/src/models/train_new.py 	\
  --num_train_epochs 10 \
	--output_dir "/kaggle/working/"  \
	--log_file "./logs" \
	--train_files "/kaggle/input/data-test-gradient/train.json"\
	--val_files "/kaggle/input/data-test-gradient/val.json"\
  --per_device_train_batch_size 16 \
  --per_device_eval_batch_size 16 \
	--num_beams   4 \
	--weight_decay  0.3 \
	--learning_rate 5e-5 \
	--gradient_accumulation_steps 4 \
	--with_tracking  \
	--report_to wandb \
	--checkpointing_steps epoch \
	--do_eval_per_epoch \
	--exp_name test